graph TD
  subgraph vue-daisy(main)
    .github
    assets
    components
    node_modules
    src
    .gitignore
    index.html
    map.mmd
    package-lock.json
    package.json
    postcss.config.js
    README.md
    tailwind.config.js
    vite.config.js
  end
  assets --> eu2.jpg
  assets --> favicon.ico
  assets --> hero-bg.fw.png
  assets --> hero-bg.jpg
  components --> App.vue
  components --> Footer.vue
  components --> Main.vue
  components --> Navbar.vue


---

'map.lua'

🗂️ vue-daisy(main)
├── 📁 .github
├── 📂 assets
│   ├── 🖼️ eu2.jpg
│   ├── 🖼️ favicon.ico
│   ├── 🌆 hero-bg.fw.png
│   ├── 🌅 hero-bg.jpg
├── 📁 components
│   ├── 🔰 App.vue
│   ├── 🔰 Footer.vue
│   ├── 🔰 Main.vue
│   ├── 🔰 Navbar.vue
├── 📂 node_modules
├── 📁 src
│   ├── 📑 app.css
│   ├── 📃 main.js
├── 🚫 .gitignore
├── 🌐 index.html
├── 🗺️ map.mmd
├── 🔐 package-lock.json
├── 💼 package.json
├── 💾 postcss.config.js
├── 📄 README.md
├── 💾 tailwind.config.js
└── 💾 vite.config.js
